### ISSUE TITLE
HTML table sorting appears broken

### ISSUE THREAD

**Issue by Sir-Teatei-Moonlight** [vaxherd/xb3tool#38]
Click-to-sort table headers do not appear to work.

Compare:
* (XC1 table that works) https://xenoblade.github.io/xb1/bdat/bdat_common/BTL_bufflist.html
* (XC3 table that doesn't work) https://xenobladedata.github.io/xb3_200_dlc4/CHR_PC.html

**Comment by vaxherd** [comment]
Working as intended; the sorting code in the XbTool HTML doesn't work for me either (browser issue, perhaps?), but I never found a need to sort anyway so I didn't copy it over.
